[package]
name = "e0521e/mutils"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/e0521e/mutils.git"
realm = "shared"
description = "my utils"
license = "MIT"
authors = ["am"]

[dependencies]
#
[files]
include = ["src"]
exclude = []
